apiVersion: v1
kind: Service
metadata:
  name: messaging-operator-webhook
  namespace: operator-system
spec:
  selector:
    app: messaging-operator-webhook
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
