apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkaclusters.{{ .Values.apiGroup }}
  labels:
    {{- include "messaging-operator.labels" . | nindent 4 }}
spec:
  group: {{ .Values.apiGroup }}
  names:
    kind: KafkaCluster
    plural: kafkaclusters
    singular: kafkacluster
    shortNames:
      - vc
  scope: Namespaced
  versions:
    - name: {{ .Values.apiVersion }}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - clusterId
                - applicationServiceRef
              properties:
                clusterId:
                  type: string
                  description: Conduktor Virtual Cluster ID
                applicationServiceRef:
                  type: string
                  description: Reference to ApplicationService CR
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: Current phase of the resource
                message:
                  type: string
                  description: Status message
      subresources:
        status: {}
